var STAR_TREK_LOREM_IPSUM_ARRAY = [
  'Communication is not possible. The shuttle has no power. Using the gravitational pull of a star to slingshot back in time? \n We are going to Starbase Montgomery for Engineering consultations prompted by minor read-out anomalies. Probes have recorded unusual levels of geological activity in all five planetary systems. Assemble a team. Look at records of the Drema quadrant. Would these scans detect artificial transmissions as well as natural signals?',
  'Sensors indicate no shuttle or other ships in this sector. According to coordinates, we have travelled 7,000 light years and are located near the system J-25. Tractor beam released, sir. Force field maintaining our hull integrity. Damage report? Sections 27, 28 and 29 on decks four, five and six destroyed. Without our shields, at this range it is probable a photon detonation could destroy the Enterprise.',
  "We're acquainted with the wormhole phenomenon, but this... Is a remarkable piece of bio-electronic engineering by which I see much of the EM spectrum ranging from heat and infrared through radio waves, et cetera, and forgive me if I've said and listened to this a thousand times. This planet's interior heat provides an abundance of geothermal energy. We need to neutralize the homing signal.",
  "Sensors indicate human life forms 30 meters below the planet's surface. Stellar flares are increasing in magnitude and frequency. Set course for Rhomboid Dronegar 006, warp seven. There's no evidence of an advanced communication network. Total guidance system failure, with less than 24 hours' reserve power. Shield effectiveness has been reduced 12 percent. We have covered the area in a spherical pattern which a ship without warp drive could cross in the given time.",
  'Exceeding reaction chamber thermal limit. We have begun power-supply calibration. Force fields have been established on all turbo lifts and crawlways. Computer, run a level-two diagnostic on warp-drive systems. Antimatter containment positive. Warp drive within normal parameters. I read an ion trail characteristic of a freighter escape pod. The bomb had a molecular-decay detonator. Detecting some unusual fluctuations in subspace frequencies.',
  "It indicates a synchronic distortion in the areas emanating triolic waves. The cerebellum, the cerebral cortex, the brain stem,  the entire nervous system has been depleted of electrochemical energy. Any device like that would produce high levels of triolic waves. These walls have undergone some kind of selective molecular polarization. I haven't determined if our phaser energy can generate a stable field. We could alter the photons with phase discriminators.",
  "Run a manual sweep of anomalous airborne or electromagnetic readings. Radiation levels in our atmosphere have increased by 3,000 percent. Electromagnetic and subspace wave fronts approaching synchronization. What is the strength of the ship's deflector shields at maximum output? The wormhole's size and short period would make this a local phenomenon. Do you have sufficient data to compile a holographic simulation?",
  "A library serves no purpose unless someone is using it. Without followers, evil cannot spread. Instruments register only through things they're designed to register. Space still contains infinite unknowns. Khaaannnn! So much for the little training cruise. I’ve done far worse than kill you. …I’ve hurt you; and I intend to go on… hurting you. I will leave you as you left me; as you left her. Marooned for all eternity at the center of a dead planet. …Buried alive; buried alive….",
  "Sometimes a feeling is all we humans have to go on. Humans do have an amazing capacity for believing what they choose -- and excluding that which is painful. Curious, how often you humans manage to obtain that which you do not want. Look at these three words written larger than all the rest, and with special pride never written before or since -- tall words, proudly saying 'We the people' ... these words and the words that follow ... must apply to everyone or they mean nothing. Make It So! He tasks me. He tasks me; and I shall have him. I’ll chase him ’round the moons of Nibia and ’round the Antares maelstrom and ’round Perdition’s flames before I give him up.",
  "A man either lives life as it happens to him, meets it head-on and licks it, or he turns his back on it and starts to wither away. You may find that having is not so pleasing a thing as wanting. This is not logical, but it is often true. A library serves no purpose unless someone is using it. Insufficient facts always invite danger. They used to say that if Man was meant to fly, he'd have wings. But he did fly. He discovered he had to. In critical moments, men sometimes see exactly what they wish to see. We're a most promising species, Mr. Spock, as predators go. Did you know that? I frequently have my doubts. I don't. Not any more. And maybe in a thousand years or so, we'll be able to prove it. Khaaannnn! Resistance Is Futile! It’s a — far, far better thing I do than I have ever done before; a far better resting place I go to than I have ever known.” “…Is that a poem?” “…Mmm. Something Spock was trying to tell me — on my birthday.",
  "If we're going to be damned, let's be damned for what we really are. Compassion: that's the one things no machine ever had. Maybe it's the one thing that keeps men ahead of them. Curious, how often you humans manage to obtain that which you do not want. One man cannot summon the future. But one man can change the present!  A species that enslaves other beings is hardly superior -- mentally or otherwise. For everything, there is a first time. So much for the little training cruise.",
  "When a child is taught, it's programmed with simple instructions, and at some point, if its mind develops properly, it exceeds the sum of what it was taught, thinks independently. The intellect is not all... but its cultivation must come first, or the individual makes errors... wastes time in unprofitable pursuits. Khaaannnn! I'm Givin' Her All She's Got, Captain! Resistance Is Futile! For everything, there is a first time. So much for the little training cruise.",
  "We're a most promising species, Mr. Spock, as predators go. Did you know that? I frequently have my doubts. I don't. Not any more. And maybe in a thousand years or so, we'll be able to prove it. To all mankind -- may we never find space so vast, planets so cold, heart and mind so empty that we cannot fill them with love and warmth. Improve a mechanical device and you may double productivity. But improve man, you gain a thousandfold. So much for the little training cruise. No, Kirk, no. You’ll not escape. From hell’s heart, I stab at thee. …For spite’s sake, I spit my last breath at thee.",
  "When dreams become more important than reality, you give up travel, building, creating; you even forget how to repair the machines left behind by your ancestors. You just sit living and reliving other lives left behind in the thought records. Madness has no purpose. Or reason. But it may have a goal. Insults are effective only where emotion is present. Compassion: that's the one things no machine ever had. Maybe it's the one thing that keeps men ahead of them. No, Kirk, no. You’ll not escape. From hell’s heart, I stab at thee. …For spite’s sake, I spit my last breath at thee.",
  "I haven't faced death. I've cheated death. I've tricked my way out of death and patted myself on the back for my ingenuity; I know nothing. Computers make excellent and efficient servants, but I have no wish to serve under them. ... the prejudices people feel about each other disappear when they get to know each other. A library serves no purpose unless someone is using it. It's time you learned that freedom is never a gift. It has to be earned. Improve a mechanical device and you may double productivity. But improve man, you gain a thousandfold. You’ve never really faced death, have you?” “...No; not like this. I haven’t faced death. I’ve cheated death. I’ve tricked my way out of death and patted myself on the back for my ingenuity; I know nothing. ",
  "Leave bigotry in your quarters; there's no room for it on the bridge. In critical moments, men sometimes see exactly what they wish to see. Without followers, evil cannot spread. Human beings do not survive on bread alone ... but on the nourishments of liberty. For what indeed is a man without freedom ... naught but a mechanism, trapped in the cogwheels of eternity. It's time you learned that freedom is never a gift. It has to be earned. Without freedom of choice there is no creativity.",
  "Perhaps man wasn't meant for paradise. Maybe he was meant to claw, to scratch all the way. One man cannot summon the future. But one man can change the present!  Your will to survive, your love of life, your passion to know ... Everything that is truest and best in all species of beings has been revealed to you. Those are the qualities that make a civilization worthy to survive. It was the best of times, it was the worst of times.’ …Message, Spock?” “…None that I am conscious of — save, perhaps, for ‘Happy Birthday.‘",
  "Logic is the beginning of wisdom, not the end. Genius doesn't work on an assembly line basis. Did Einstein, Kazanga or Sitar of Vulcan produce new and revolutionary theories on a regular schedule? You can't simply say, 'Today I will be brilliant.' Compassion: that's the one things no machine ever had. Maybe it's the one thing that keeps men ahead of them.",
];


/**
 * Returns a random quote from the Star Trek.
 * @example
 * // returns "Sensors indicate human life forms 30 meters below the planet's surface..."
 * getStarTrekQuote();
 * @returns {String} A random quote from Star Trek in the form of a String.
 */
function getStarTrekQuote() {
  var randomArrayElementNumber = Math.floor(
    Math.random() * STAR_TREK_LOREM_IPSUM_ARRAY.length,
  );
  return STAR_TREK_LOREM_IPSUM_ARRAY[randomArrayElementNumber];
}


module.exports = getStarTrekQuote;